APPLICATION := mooshak-cli
LIBRARY := libmooshak

all: $(APPLICATION)/$(APPLICATION)

$(LIBRARY)/$(LIBRARY).a: $(LIBRARY)/*.c
	$(MAKE) -C $(LIBRARY)/

$(APPLICATION)/$(APPLICATION): $(APPLICATION)/*.c $(LIBRARY)/$(LIBRARY).a
	$(MAKE) -C $(APPLICATION)/

.PHONY: clean
clean:
	$(MAKE) -C $(APPLICATION)/ clean
	$(MAKE) -C $(LIBRARY)/ clean

.PHONY: run
run:
	./$(APPLICATION)/$(APPLICATION)

