.TH "mooshak_ctx_s" 3 "Mon Oct 28 2024" "libmooshak" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mooshak_ctx_s
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBinit\fP"
.br
.ti -1c
.RI "char * \fBendpoint\fP"
.br
.ti -1c
.RI "CURL * \fBcurl\fP"
.br
.ti -1c
.RI "char * \fBlasterr\fP"
.br
.ti -1c
.RI "CURLcode \fBlaststat\fP"
.br
.ti -1c
.RI "\fBbuff_t\fP \fBresbuff\fP"
.br
.in -1c
.SH "Field Documentation"
.PP 
.SS "CURL* mooshak_ctx_s::curl"

.SS "char* mooshak_ctx_s::endpoint"

.SS "int mooshak_ctx_s::init"

.SS "char* mooshak_ctx_s::lasterr"

.SS "CURLcode mooshak_ctx_s::laststat"

.SS "\fBbuff_t\fP mooshak_ctx_s::resbuff"


.SH "Author"
.PP 
Generated automatically by Doxygen for libmooshak from the source code\&.
