.TH "mooshak_submission_t" 3 "Mon Oct 28 2024" "libmooshak" \" -*- nroff -*-
.ad l
.nh
.SH NAME
mooshak_submission_t
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <libmooshak\&.h>\fP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "int \fBid\fP"
.br
.ti -1c
.RI "time_t \fBtime\fP"
.br
.ti -1c
.RI "char * \fBcountry\fP"
.br
.ti -1c
.RI "char * \fBteam\fP"
.br
.ti -1c
.RI "char * \fBproblem\fP"
.br
.ti -1c
.RI "char * \fBlanguage\fP"
.br
.ti -1c
.RI "char * \fBresult\fP"
.br
.ti -1c
.RI "char * \fBstate\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Submission list item type 
.SH "Field Documentation"
.PP 
.SS "char* mooshak_submission_t::country"
Submitter country 
.SS "int mooshak_submission_t::id"
Sequential ID 
.SS "char* mooshak_submission_t::language"
Submission language 
.SS "char* mooshak_submission_t::problem"
Problem submit 
.SS "char* mooshak_submission_t::result"
Test result 
.SS "char* mooshak_submission_t::state"
Submission state 
.SS "char* mooshak_submission_t::team"
Submitter team 
.SS "time_t mooshak_submission_t::time"
Submission time 

.SH "Author"
.PP 
Generated automatically by Doxygen for libmooshak from the source code\&.
